namespace XFlag.Alter3Simulator
{
    public enum CommandType
    {
        AddAxis,
        AppendAxis,
        GetAxis,
        Hello,
        Help,
        MoveAxis,
        MoveAxes,
        Noop,
        PlayMotion,
        PrintQueue,
        Quit,
        ClearQueue,
        ClientsInfo,
        ConnectRobot,
        DisconnectRobot,
        IsConnected,
        IsRecordingMotion,
        RecordMotion,
        ResetPose,
        RobotInfo,
        WhoAmI,
        Calib,
        GetPositions
    }
}
